### ISSUE TITLE
Tuesday 09-05-2023- rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#120]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by ervinMamutov** [comment]
hi

**Comment by inna9Z** [comment]
I am here

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by Rekhasriraman** [comment]
Hello

**Comment by PreethiTapati** [comment]
good morning

**Comment by ZahiraBella** [comment]
good morning

**Comment by Mileenka** [comment]
Today we finish planning HYF project and start coding :) let's do it 💯

**Comment by Mariya-go** [comment]
Good morning.

**Comment by iradukundajp** [comment]
Good morning!

**Comment by cristobal-lopez** [comment]
here

**Comment by Rahwakinfe** [comment]
hello

**Comment by himanshisaxena** [comment]
Good morning

**Comment by khalidkhan1212** [comment]
present

**Comment by komal-89** [comment]
hello

**Comment by Abdul-MalikSardalov** [comment]
Here
