### ISSUE TITLE
Wednesday 10-05-2023- rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#122]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Hi everyone on this beautiful rainy day. 🌧️ We are glad that we have online lessons and we don't have to leave the house. 🤣  Article about breakpoint might be of interest ---> 👩‍💻  https://getbootstrap.com/docs/5.2/layout/breakpoints/

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Rekhasriraman** [comment]
Good morning

**Comment by komal-89** [comment]
Good morning

**Comment by PreethiTapati** [comment]
good morning

**Comment by Rahwakinfe** [comment]
good morning

**Comment by iradukundajp** [comment]
Good morning !

**Comment by ervinMamutov** [comment]
I am online

**Comment by ZahiraBella** [comment]
good morning

**Comment by Abdul-MalikSardalov** [comment]
Online

**Comment by Rahatab** [comment]
Hello

**Comment by khalidkhan1212** [comment]
present

**Comment by inna9Z** [comment]
Present

**Comment by himanshisaxena** [comment]
Present

**Comment by samirm00** [comment]
Cristobal is present
