### ISSUE TITLE
Friday 12-05-2023- rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#123]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by himanshisaxena** [comment]
Good morning

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by Rahwakinfe** [comment]
Morning

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Mileenka** [comment]
Good morning everyone, I am sending you a lot of positive energy for today. 🤗

**Comment by Mariya-go** [comment]
:+1:  :100:

**Comment by Rahatab** [comment]
Hello every one

**Comment by inna9Z** [comment]
Present

**Comment by cristobal-lopez** [comment]
present!

**Comment by iradukundajp** [comment]
Good morning!

**Comment by ervinMamutov** [comment]
Good rainy morning

**Comment by khalidkhan1212** [comment]
present

**Comment by PreethiTapati** [comment]
Good Morning

**Comment by komal-89** [comment]
Good morning

**Comment by Abdul-MalikSardalov** [comment]
Present

**Comment by Rekhasriraman** [comment]
Hello

**Comment by ZahiraBella** [comment]
good morning
