### ISSUE TITLE
Monday 15-05-2023- rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#127]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by PreethiTapati** [comment]
Good morning.  Looking forward into this week to learn more about HTML5 and CSS

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Rahatab** [comment]
morning

**Comment by himanshisaxena** [comment]
Good morning

**Comment by Mileenka** [comment]
Hi everyone :)

**Comment by Abdul-MalikSardalov** [comment]
I'm here

**Comment by VladyslavHornitskyi** [comment]
Onsite

**Comment by ervinMamutov** [comment]
Hi

**Comment by inna9Z** [comment]
Present

**Comment by Rekhasriraman** [comment]
Good morning

**Comment by khalidkhan1212** [comment]
Present

**Comment by ZahiraBella** [comment]
good morning

**Comment by Mariya-go** [comment]
Good morning

**Comment by FernandoYsita** [comment]
good morning

**Comment by cristobal-lopez** [comment]
I'm here!
