### ISSUE TITLE
Tuesday 16-05-2023 - roll call

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#148]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by PreethiTapati** [comment]
good morning

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Rekhasriraman** [comment]
Good morning

**Comment by Mileenka** [comment]
Hello on this beautiful sunny day.  ☀️ I hope you are all feeling well today 🤗

**Comment by Mariya-go** [comment]
Good morning everyone.

**Comment by FernandoYsita** [comment]
good morning

**Comment by komal-89** [comment]
Good morning

**Comment by khalidkhan1212** [comment]
present

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by himanshisaxena** [comment]
Good morning

**Comment by ZahiraBella** [comment]
good morning

**Comment by iradukundajp** [comment]
Good morning!

**Comment by inna9Z** [comment]
present

**Comment by ervinMamutov** [comment]
Hi

**Comment by Abdul-MalikSardalov** [comment]
🤯🥲🙂

**Comment by Rahwakinfe** [comment]
morning
