### ISSUE TITLE
Monday 22-05-2023 -roll call

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#170]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by khalidkhan1212** [comment]
present

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Rahwakinfe** [comment]
good morning

**Comment by ZahiraBella** [comment]
good morning

**Comment by inna9Z** [comment]
Good morning

**Comment by Rahatab** [comment]
morning

**Comment by Mileenka** [comment]
Hi ! Enjoy your coffee and have a beautiful day <3

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by himanshisaxena** [comment]
Good morning

**Comment by cristobal-lopez** [comment]
Good morning. Present!

**Comment by PreethiTapati** [comment]
Good morning

**Comment by Mariya-go** [comment]
Good morning

**Comment by Abdul-MalikSardalov** [comment]
👋🏼

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by ervinMamutov** [comment]
hi
