### ISSUE TITLE
Wedensday 31-05-2023 rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#194]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by khalidkhan1212** [comment]
Present

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by Rahwakinfe** [comment]
good morning

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by inna9Z** [comment]
good morning

**Comment by komal-89** [comment]
good morning

**Comment by FernandoYsita** [comment]
hello

**Comment by iradukundajp** [comment]
Morning

**Comment by ervinMamutov** [comment]
hi

**Comment by Rahatab** [comment]
morning

**Comment by Mileenka** [comment]
Good morning, enjoy a beautiful day 🌞

**Comment by cristobal-lopez** [comment]
I am here!

**Comment by ZahiraBella** [comment]
hello

**Comment by Abdul-MalikSardalov** [comment]
: )

**Comment by himanshisaxena** [comment]
I am here
