### ISSUE TITLE
Cris : Welcome to JS : Calculator

### ISSUE THREAD

**Issue by cristobal-lopez** [BF-FrontEnd-class/home#202]
- [x] [repo](https://github.com/cristobal-lopez/JS-simple-calculator) 
- [x] [live demo](https://cristobal-lopez.github.io/JS-simple-calculator/)
- [x] [project board](https://github.com/orgs/BF-FrontEnd-class/projects/2)

**Comment by samirm00** [comment]
@cristobal-lopez  as I told you. You don't need `async defer`  and also you can make your input `read-only`

**Comment by cristobal-lopez** [comment]
@samirm00 understood. Thanks
