### ISSUE TITLE
Maria : Welcome to JS : Calculator

### ISSUE THREAD

**Issue by Mariya-go** [BF-FrontEnd-class/home#203]
- [x] [repo](https://github.com/Mariya-go/Calculator) 
- [x] [live demo](https://mariya-go.github.io/Calculator/))
- [x] [project board](https://github.com/users/Mariya-go/projects/5))

**Comment by Mariya-go** [comment]
I did it last week but forgot to move to ready for review, sorry

**Comment by samirm00** [comment]
it is Maria, no worries, good job.
