### ISSUE TITLE
Thursday 15-06-2023 roll call 

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#225]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by PreethiTapati** [comment]
good morning

**Comment by ervinMamutov** [comment]
hi

**Comment by ZahiraBella** [comment]
hi

**Comment by himanshisaxena** [comment]
Good morning

**Comment by komal-89** [comment]
present

**Comment by Mariya-go** [comment]
Good morning

**Comment by Rahwakinfe** [comment]
GOOD MORNING

**Comment by cristobal-lopez** [comment]
Present! 🙋‍♂️

**Comment by khalidkhan1212** [comment]
Present

**Comment by Mileenka** [comment]
Good Morning 🌴 🌞

**Comment by iradukundajp** [comment]
Good  morning!

**Comment by inna9Z** [comment]
Present

**Comment by Rahatab** [comment]
morning

**Comment by Abdul-MalikSardalov** [comment]
👋🏼
