### ISSUE TITLE
Thursday  29-06-2023   roll call 

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#232]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by ervinMamutov** [comment]
hi

**Comment by khalidkhan1212** [comment]
present

**Comment by Mariya-go** [comment]
hello

**Comment by inna9Z** [comment]
present

**Comment by PreethiTapati** [comment]
Hello.

**Comment by Rekhasriraman** [comment]
Hello

**Comment by komal-89** [comment]
hello

**Comment by Mileenka** [comment]
Present

**Comment by IrynaSobetska** [comment]
Hello

**Comment by Abdul-MalikSardalov** [comment]
console.log( ` i'm present ` ) ;

**Comment by himanshisaxena** [comment]
Hello

**Comment by iradukundajp** [comment]
Present

**Comment by Rahatab** [comment]
hello
