### ISSUE TITLE
Group3 : Stop-Watch

### ISSUE THREAD

**Issue by inna9Z** [BF-FrontEnd-class/home#255]
- [x] [repo](https://github.com/BF-FrontEnd-class/stop-watch-group-3) (with a complete README)
- [x] [live demo](https://bf-frontend-class.github.io/stop-watch-group-3/)
- [x] [project board](https://github.com/orgs/BF-FrontEnd-class/projects/31/views/1?layout=board)

**Comment by samirm00** [comment]
Good job, although you make it a little bite complex, but it is really good.
