### ISSUE TITLE
Monday 24-07-2023 roll call

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#259]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by FernandoYsita** [comment]
Morning

**Comment by ervinMamutov** [comment]
hi

**Comment by IrynaSobetska** [comment]
Morning

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by cristobal-lopez** [comment]
present!

**Comment by himanshisaxena** [comment]
Good morning

**Comment by PreethiTapati** [comment]
good morning

**Comment by komal-89** [comment]
present

**Comment by Mariya-go** [comment]
Good morning

**Comment by iradukundajp** [comment]
Good morning !

**Comment by Mileenka** [comment]
Good morning everyone 🖤

**Comment by inna9Z** [comment]
present

**Comment by Abdul-MalikSardalov** [comment]
present

**Comment by khalidkhan1212** [comment]
present
