### ISSUE TITLE
Tuesday 25-07-2023 roll call

### ISSUE THREAD

**Issue by Mileenka** [BF-FrontEnd-class/home#274]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by inna9Z** [comment]
present

**Comment by Mileenka** [comment]
Good morning :)

**Comment by IrynaSobetska** [comment]
Present

**Comment by ervinMamutov** [comment]
hi

**Comment by PreethiTapati** [comment]
GOOD MORNING

**Comment by cristobal-lopez** [comment]
present

**Comment by komal-89** [comment]
present

**Comment by himanshisaxena** [comment]
Good morning

**Comment by iradukundajp** [comment]
Morning!

**Comment by FernandoYsita** [comment]
MOrning

**Comment by Mariya-go** [comment]
good morning

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by khalidkhan1212** [comment]
Present

**Comment by Abdul-MalikSardalov** [comment]
Was there
