### ISSUE TITLE
Friday 04-08-2023

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#293]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Goood morning 🌺 i wish you all beautiful Friday ❤️

**Comment by ervinMamutov** [comment]
hi

**Comment by cristobal-lopez** [comment]
present

**Comment by PreethiTapati** [comment]
good morning

**Comment by himanshisaxena** [comment]
Good Morning

**Comment by inna9Z** [comment]
present

**Comment by komal-89** [comment]
present

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by khalidkhan1212** [comment]
Present

**Comment by Rekhasriraman** [comment]
Hello

**Comment by FernandoYsita** [comment]
Hey

**Comment by iradukundajp** [comment]
Present!

**Comment by Abdul-MalikSardalov** [comment]
🤝🏼

**Comment by FernandoYsita** [comment]
Hola
