### ISSUE TITLE
Group1: Workflows : Intro

### ISSUE THREAD

**Issue by FernandoYsita** [BF-FrontEnd-class/home#39]
**Group1**
**Project** : *Intro*
**Project leader**: [Fernando](https://github.com/FernandoYsita)
**Members**: 
- [Vlad](https://github.com/VladyslavHornitskyi)
- [ Preethi ](https://github.com/preethimadhuri2289)
- [ Rahwa](https://github.com/Rahwakinfe)
- [ Himanshi](https://github.com/himanshisaxena)
- --
- [x] [repo](https://github.com/BF-FrontEnd-class/workflows-group1-intro)
- [x] [issues](https://github.com/BF-FrontEnd-class/workflows-group1-intro/issues)
- [x] a nice README
- [x] one well-named file per person
- [x] [one pull requests for each group member](https://github.com/BF-FrontEnd-class/workflows-group1-intro/pulls)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code

**Comment by samirm00** [comment]
Before you move your issue to `Ready for review , you have to close all your issue and move them to `Done`
