### ISSUE TITLE
Wednesday 20-09-2023 roll call 

### ISSUE THREAD

**Issue by sammou00** [BF-FrontEnd-class/home#396]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Hello 🙋‍♀️🌼

**Comment by alexander-lopez-s** [comment]
Present!

**Comment by PreethiTapati** [comment]
Good morning

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by khalidkhan1212** [comment]
present

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by Mariya-go** [comment]
Good morning

**Comment by ervinMamutov** [comment]
hi

**Comment by komal-89** [comment]
hi

**Comment by inna9Z** [comment]
present

**Comment by FernandoYsita** [comment]
hi

**Comment by Abdul-MalikSardalov** [comment]
🤝

**Comment by iradukundajp** [comment]
Present
