### ISSUE TITLE
Group 2 : Workflows : Intro 

### ISSUE THREAD

**Issue by ZahiraBella** [BF-FrontEnd-class/home#42]
**Group2**
**Project** : *Intro*
**Project leader**: [Zahira Bella](https://github.com/ZahiraBella)
**Members**: 
- [Karol ](https://github.com/karol10cano)
- [Milena](https://github.com/Mileenka)
- [Maria](https://github.com/Mariya-go)
- --
- [x] [repo](https://github.com/BF-FrontEnd-class/workflows-group2-intro)
- [x] [issues](https://github.com/BF-FrontEnd-class/workflows-group2-intro/issues)
- [x] a nice README
- [x] one well-named file per person
- [x] [one pull requests for each group member](https://github.com/BF-FrontEnd-class/workflows-group2-intro/pulls)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code

**Comment by samirm00** [comment]
You had one open `PR`, I closed it, but before you move your project to `Ready for review` all `PR` must be merged.
