### ISSUE TITLE
Friday 28-04-2023-rollCall 

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#81]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by ervinMamutov** [comment]
hi

**Comment by VladyslavHornitskyi** [comment]
online

**Comment by PreethiTapati** [comment]
Good morning. I am here

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by inna9Z** [comment]
Good morning , I am here .

**Comment by FernandoYsita** [comment]
Good morning

**Comment by iradukundajp** [comment]
Present

**Comment by komal-89** [comment]
Good morning , I am here

**Comment by Mileenka** [comment]
Hi everyone, today we end our first week. The first hardest step is behind us. It will only get better now. Together we strive for the same goal, so with mutual support we can do it 😄 . Now take your coffee ☕  and get to work, it's not gonna do itself. 
https://www.shecancode.io/blog/guide-to-git-and-github-10-github-tricks-you-should-know

**Comment by karol10cano** [comment]
👍🏻 I'm here

**Comment by himanshisaxena** [comment]
hello, i am here

**Comment by Rahwakinfe** [comment]
i have nothing to share today hello for today

**Comment by Rekhasriraman** [comment]
Good Morning

**Comment by ZahiraBella** [comment]
hello ! today we will learn more about who to work with github and get more familiar ,
thanks Samir for your support

**Comment by Mariya-go** [comment]
Good morning. 
Maybe it's will be useful for somebody a list of terminal command 
https://www.guru99.com/linux-commands-cheat-sheet.html#1

**Comment by khalidkhan1212** [comment]
i,m on

**Comment by Abdul-MalikSardalov** [comment]
Have a good day
