### ISSUE TITLE
Tuesday 02-05-2023- roll Call

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#83]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by PreethiTapati** [comment]
Good morning. I am here

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by ZahiraBella** [comment]
Good Morning! I'm ready to start this week and learn about Agile Methodology.

**Comment by Mileenka** [comment]
Starting another week with new energy. :muscle: I wish all of us that knowledge enters our heads at the speed of light and you, Samir, a lot of patience. :sweat_smile: .Let's start with Agile :)

**Comment by ervinMamutov** [comment]
Hi

**Comment by Rahwakinfe** [comment]
here

**Comment by himanshisaxena** [comment]
Good Morning

**Comment by FernandoYsita** [comment]
Hello good morning, I'm ready to learn new methodology

**Comment by khalidkhan1212** [comment]
present

**Comment by IrynaSobetska** [comment]
Good morning, I'm happy to start the new module with all of you :yum:

**Comment by iradukundajp** [comment]
Good morning!

**Comment by Abdul-MalikSardalov** [comment]
good morning

**Comment by karol10cano** [comment]
Im here!
