### ISSUE TITLE
group4 : agile-development : loruki-rebuild

### ISSUE THREAD

**Issue by Abdul-MalikSardalov** [BF-FrontEnd-class/home#89]
- [x] [repo](https://github.com/BF-FrontEnd-class/agile-development-group4-loruki-rebuild/) (with a complete README)
- [x] [live demo](https://github.com/BF-FrontEnd-class/agile-development-group4-loruki-rebuild/) (GitHub Pages, not Netlify)
- [/planning](https://github.com/BF-FrontEnd-class/agile-development-group4-loruki-rebuild/tree/main/planning)
  - [x] constraints
  - [x] communication plan
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/orgs/BF-FrontEnd-class/projects/22)

**Comment by samirm00** [comment]
@Abdul-MalikSardalov Very good job.
