### ISSUE TITLE
Friday 05-05-2023- rollCall

### ISSUE THREAD

**Issue by samirm00** [BF-FrontEnd-class/home#96]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Hello everyone.  Let's go to finish our projects 😃 🔥

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by VladyslavHornitskyi** [comment]
Online

**Comment by FernandoYsita** [comment]
im here

**Comment by karol10cano** [comment]
Present!

**Comment by Rahwakinfe** [comment]
Good morning

**Comment by komal-89** [comment]
Good morning

**Comment by ervinMamutov** [comment]
Hi

**Comment by Rekhasriraman** [comment]
Good morning

**Comment by PreethiTapati** [comment]
Good Morning

**Comment by ZahiraBella** [comment]
good morning

**Comment by himanshisaxena** [comment]
good morning

**Comment by inna9Z** [comment]
good morning, I am here

**Comment by khalidkhan1212** [comment]
present

**Comment by cristobal-lopez** [comment]
present

**Comment by iradukundajp** [comment]
Morning

**Comment by Rahatab** [comment]
i am here

**Comment by Abdul-MalikSardalov** [comment]
here

**Comment by Mariya-go** [comment]
I am here
